version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  sylius:
    build: .
    volumes:
      - ${PWD}/sylius:/usr/src/sylius:cached
  mysql:
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sylius
      MYSQL_DATABASE: sylius
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius
    ports:
      - 127.0.0.1:3306:3306
