version: '2'

services:
  sylius:
    build: .
    environment:
      - SYLIUS_DATABASE_HOST=mysql
      - SYLIUS_DATABASE_USER=sylius
      - SYLIUS_DATABASE_PASSWORD=sylius
      - SYLIUS_MAILER_HOST=mailhog:1025
      - SYLIUS_APP_DEV_PERMITTED=1
    ports:
      - 8000:80

  mysql:
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sylius
      MYSQL_DATABASE: sylius_dev
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius
    ports:
      - 127.0.0.1:3306:3306

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
